name: DarkGlass
description: A sample web application
dependencies:
  browser: any
  http-server: any
  html5lib: any
  google_mirror_v1_api: '>=0.4.8 <0.5.0'
  google_plus_v1_api:
    git: https://github.com/dartglass/dart_plus_v1_api_client.git
